title: Ajinkya Mishrikotkar # your name (or website title) here
logo: "/Images/Title_pic.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist 
  <br><br>
  I am currently working as Machine Learning Engineer at Digitalmain.I have an expertise on NLP domain.
  <br><br>
  <a href="https://www.linkedin.com/in/ajinkya-mishrikotkar-a6594a144/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://ajinkya29.medium.com/">View My Medium Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
